### ISSUE TITLE
how do i read the files

### ISSUE THREAD

**Issue by Anthonity** [Bean0of/deathmarkers#14]
i wanted to look through the files using notepad to look at my fails on a level but its showing gibberish

**Comment by Adam7290** [comment]
The file format is in binary, you have to read it via a hex editor tool like [hxd](https://mh-nexus.de/en/hxd/).
```c++
// DI file format
// DI stands for "Death Indicators" back when this mod was called that
struct DIPoint {
	float x, y;
};

struct DIFile {
	uint32_t length;
	DIPoint points[];
};
```

**Comment by Anthonity** [comment]
how do i read it in hxd

**Comment by Anthonity** [comment]
never mind i made a script for that
