### ISSUE TITLE
dont go away

### ISSUE THREAD

**Issue by GockelDS2** [Bean0of/deathmarkers#16]
i tried deinstalling the mod because the markers were annoying, but even after deinstalling it they wont dissapear. I deinstalled gd an installed it again and they still are there why?

**Comment by Adam7290** [comment]
Do you by any chance have "Death Replay" installed? Apparently it has a similar feature.

**Comment by GockelDS2** [comment]
Oh sorry, i didnt knew that. It was Death replay…Am 07.05.2024 um 01:58 schrieb Adam_729 ***@***.***>:﻿
Do you by any chance have "Death Replay" installed? Apparently it has a similar feature.
