### ISSUE TITLE
Suggestion: Option to remove outline

### ISSUE THREAD

**Issue by gonkergd** [Bean0of/deathmarkers#4]
Some people prefer it without outline. Oh and, in the real game, there is no black outline on the markers too.

**Comment by Adam7290** [comment]
you can just make a [resource pack](https://github.com/geode-sdk/textureldr)

**Comment by Adam7290** [comment]
ok i quickly made some texture packs
https://github.com/Bean0of/deathmarkers/tree/main/texturepacks
