### ISSUE TITLE
Dead marker cancels Option trigger respawn time

### ISSUE THREAD

**Issue by NonCloud9** [Bean0of/deathmarkers#7]
When i was tweking with the reset/respawn time from the options trigger and try to test it on the level, i see the respawn time is always the same even if you put a long time for the respawn time.

Also, it cancels the "Enable faster reset" option from the option menu.

https://github.com/Bean0of/deathmarkers/assets/85463024/6ff850d6-ea7b-4092-8942-0c4c37326fa0

**Comment by Adam7290** [comment]
kinda fixed
