### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Helloausername** [Bean0of/deathmarkers#9]
![Screenshot_20240211-094457_Geode](https://github.com/Bean0of/deathmarkers/assets/158708969/f66755eb-f7f9-4411-b80d-69a94fc82140)
the deathmarker is far from where I died and it isn't fixed

**Comment by Helloausername** [comment]
my icon is invisible

**Comment by Adam7290** [comment]
I said fixed for *next update* which I totally didn't forget to upload
